export const GET_TOKEN = 'GET_TOKEN';
export const CHANGE_CINEMA = 'CHANGE_CINEMA';
export const GET_CINEMAS = 'GET_CINEMAS';
export const CHANGE_MOVIE = 'CHANGE_MOVIE';
export const GET_MOVIES = 'GET_MOVIES';
export const CHANGE_UPCOMING_MOVIE = 'CHANGE_UPCOMING_MOVIE';
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
